// 제품 collector의 실제 경로와 같은 TU 내부 진단 함수를 검증한다. 공개 API 추가 없음.
#include "../../src/recording/recording_file_evidence.cpp"
#include <iostream>
#include <thread>
static void Check(bool ok,const char* label){if(!ok)throw std::runtime_error(label);std::cout<<"[pass] "<<label<<'\n';}
static std::string FinishReason(recording::RecordingFileEvidenceCollector& collector){std::string reason;const auto proof=collector.Finish({}, {},0,{},&reason);if(proof)throw std::runtime_error("failed capture unexpectedly issued proof");return reason;}
static media::Packet Packet(){media::Packet packet;packet.observation=media::SampleObservation{};packet.observation->ordinal=1;packet.observation->pts_ns=0;packet.observation->dts_ns=0;packet.observation->duration_ns=1;packet.payload={0,0,0,1,0x65,0x80};return packet;}
static GstCaps* InputCaps(const std::vector<unsigned char>& header,const char* format="avc"){
 auto* caps=gst_caps_new_simple("video/x-h264","stream-format",G_TYPE_STRING,format,"alignment",G_TYPE_STRING,"au",nullptr);auto* buffer=gst_buffer_new_allocate(nullptr,header.size(),nullptr);gst_buffer_fill(buffer,0,header.data(),header.size());gst_structure_set(gst_caps_get_structure(caps,0),"codec_data",GST_TYPE_BUFFER,buffer,nullptr);gst_buffer_unref(buffer);return caps;
}
static std::string InputReason(GstCaps* caps){try{recording::InputNalWidth(caps);return "none";}catch(const std::exception& e){return e.what();}}
static void Framing(){
 const std::string expected="51ed67cd5b18833066ee93226ffee499ecdaaefa798acbdeb21c677f4b26c136";
 Check(recording::Vcl({0,0,0,1,0x65,1,2,3},0)==expected,"F02 AnnexB literal canonical hash");
 for(unsigned width:{1,2,4}){auto* caps=InputCaps({1,66,0,30,static_cast<unsigned char>(0xfc|(width-1)),0xe0,0});Check(recording::InputNalWidth(caps)==width,("F02 caps explicit length width"+std::to_string(width)).c_str());gst_caps_unref(caps);std::vector<unsigned char> payload(width,0);payload.back()=4;payload.insert(payload.end(),{0x65,1,2,3});Check(recording::Vcl(payload,width)==expected,("F02 AVC canonical hash width"+std::to_string(width)).c_str());}
 for(unsigned width:{1,2,4}){auto* caps=InputCaps({1,66,0,30,static_cast<unsigned char>(0xfc|(width-1)),0xe0,0},"avc3");Check(recording::InputNalWidth(caps)==width,("F02 avc3 framing header width"+std::to_string(width)).c_str());gst_caps_unref(caps);}
 {auto* caps=gst_caps_from_string("video/x-h264,stream-format=byte-stream,alignment=au");Check(recording::InputNalWidth(caps)==0,"F02 explicit byte-stream width zero");gst_caps_unref(caps);}
 const std::vector<std::pair<const char*,const char*>> badCaps={{"ANY","input-caps"},{"video/x-h264,stream-format=avc,alignment=au; video/x-h264,stream-format=byte-stream,alignment=au","input-caps"},{"video/x-h265,stream-format=avc,alignment=au","input-caps"},{"video/x-h264,stream-format=avc","input-alignment"},{"video/x-h264,stream-format=avc,alignment=nal","input-alignment"},{"video/x-h264,alignment=au","input-format"},{"video/x-h264,stream-format=unknown,alignment=au","input-format"},{"video/x-h264,stream-format=avc,alignment=au","input-codec-data"},{"video/x-h264,stream-format=avc,alignment=au,codec_data=(string)bad","input-codec-data"}};
 unsigned index=0;for(const auto& item:badCaps){auto* caps=gst_caps_from_string(item.first);Check(InputReason(caps)==item.second,("F03 unsupported caps case"+std::to_string(index++)).c_str());if(caps)gst_caps_unref(caps);}
 Check(InputReason(nullptr)=="input-caps","F03 null input caps rejected");
 const std::vector<std::pair<std::vector<unsigned char>,const char*>> badHeaders={{{1,66,0,30,0xff,0xe0},"input-avcc-header"},{{2,66,0,30,0xff,0xe0,0},"input-avcc-header"},{{1,66,0,30,3,0xe0,0},"input-avcc-header"},{{1,66,0,30,0xfe,0xe0,0},"input-nal-width"}};
 index=0;for(const auto& item:badHeaders){auto* caps=InputCaps(item.first);Check(InputReason(caps)==item.second,("F03 malformed framing header case"+std::to_string(index++)).c_str());gst_caps_unref(caps);}
 {auto* caps=InputCaps({1,66,0,30,0xff,0xe0,0},"byte-stream");Check(InputReason(caps)=="input-codec-conflict","F03 byte-stream codec_data conflict rejected");gst_caps_unref(caps);}
 index=0;for(const auto& payload:std::vector<std::vector<unsigned char>>{{0,0,0},{0,0,0,0},{0,0,0,5,0x65,1,2,3}}){bool rejected=false;try{recording::Vcl(payload,4);}catch(const std::exception& e){rejected=std::string(e.what())==(index==0?"nal-header":"nal-bound");}Check(rejected,("F03 malformed AVC payload length case"+std::to_string(index++)).c_str());}
 {recording::RecordingFileEvidenceCollector c(0);auto* parser=gst_element_factory_make("h264parse",nullptr);if(!parser)throw std::runtime_error("F03 parser prerequisite");const bool attached=c.Attach(parser,nullptr);gst_object_unref(parser);c.Accept(Packet());Check(!attached&&FinishReason(c)=="capture-attach-input-caps-input-caps","F03 bad framing Attach remains failed after Accept");}
}
int main(){try{
 gst_init(nullptr,nullptr);recording::RecordingFileEvidenceCollector collector(0);media::Packet packet;collector.Accept(packet);Check(FinishReason(collector)=="capture-accept-original-fields-original-timestamp","C01 actual Accept missing observation exact phase/code");
 const char* fields[]={"pts","dts","duration","vcl"};const char* expected[]={"capture-accept-pts-timestamp-unavailable","capture-accept-dts-timestamp-unavailable","capture-accept-duration-timestamp-unavailable","capture-accept-vcl-vcl-missing"};
 for(int i=0;i<4;++i){auto bad=Packet();if(i==0)bad.observation->pts_ns=-1;if(i==1)bad.observation->dts_ns=-1;if(i==2)bad.observation->duration_ns=-1;if(i==3)bad.payload.clear();recording::RecordingFileEvidenceCollector c(0);c.Accept(bad);const auto label=std::string("C02 actual Accept ")+fields[i]+" rejected with exact reason";Check(FinishReason(c)==expected[i],label.c_str());c.Accept(Packet());Check(FinishReason(c)==expected[i],("C05 later Accept cannot overwrite "+std::string(fields[i])).c_str());}
 const char* muxReasons[]={"capture-observe-pts-timestamp-unavailable","capture-observe-dts-timestamp-unavailable","capture-observe-duration-timestamp-unavailable"};
 for(int i=0;i<3;++i){auto* buffer=gst_buffer_new();GST_BUFFER_PTS(buffer)=0;GST_BUFFER_DTS(buffer)=0;GST_BUFFER_DURATION(buffer)=1;if(i==0)GST_BUFFER_PTS(buffer)=GST_CLOCK_TIME_NONE;if(i==1)GST_BUFFER_DTS(buffer)=GST_CLOCK_TIME_NONE;if(i==2)GST_BUFFER_DURATION(buffer)=GST_CLOCK_TIME_NONE;recording::RecordingFileSampleEvidenceV1 sample;auto phase=recording::CapturePhase::ObserveLock;recording::CaptureFailure failure;try{recording::ReadMuxTimes(buffer,sample,phase);}catch(const std::exception& e){failure.Record(phase,e.what());}gst_buffer_unref(buffer);Check(failure.Reason()==muxReasons[i],("C03 shared Observe time helper "+std::string(fields[i])).c_str());}
 {auto* buffer=gst_buffer_new();GST_BUFFER_PTS(buffer)=7;GST_BUFFER_DTS(buffer)=3;GST_BUFFER_DURATION(buffer)=2;recording::RecordingFileSampleEvidenceV1 sample;auto phase=recording::CapturePhase::ObserveLock;recording::ReadMuxTimes(buffer,sample,phase);gst_buffer_unref(buffer);Check(sample.mux_pts_ns==7&&sample.mux_dts_ns==3&&sample.mux_duration_ns==2,"C03 valid Observe timestamps unchanged");}
 {recording::CaptureFailure failure;failure.Record(recording::CapturePhase::AcceptVcl,"vcl-missing");failure.Record(recording::CapturePhase::ObservePts,"timestamp-unavailable");Check(failure.Reason()=="capture-accept-vcl-vcl-missing","C04 sequential first failure wins");}
 for(int i=0;i<32;++i){recording::CaptureFailure failure;std::atomic<bool> go{false};std::thread a([&]{while(!go.load())std::this_thread::yield();failure.Record(recording::CapturePhase::AcceptVcl,"vcl-missing");});std::thread b([&]{while(!go.load())std::this_thread::yield();failure.Record(recording::CapturePhase::ObserveDts,"timestamp-unavailable");});go.store(true);a.join();b.join();const auto reason=failure.Reason();if(reason!="capture-accept-vcl-vcl-missing"&&reason!="capture-observe-dts-timestamp-unavailable")throw std::runtime_error("C04 mixed phase/code race");}Check(true,"C04 two-thread 32 races preserve one whole winner");
 for(const auto* text:{"private canary /private/path","vcl-missing suffix","timestamp-unavailable"}){recording::CaptureFailure failure;failure.Record(recording::CapturePhase::AcceptVcl,text);Check(failure.Reason()=="capture-accept-vcl-unknown","C05 arbitrary or wrong-phase exception becomes unknown");}
 Check(std::string(recording::FixedFinishReason("mp4-table-bound"))=="mp4-table-bound"&&std::string(recording::FixedFinishReason("mp4-table-bound /private/canary"))=="finish-exception","C05 Finish exact allowlist no arbitrary exception text");
 {recording::RecordingFileEvidenceCollector c(0);auto* parser=gst_element_factory_make("h264parse",nullptr);if(!parser)throw std::runtime_error("C06 parser prerequisite");auto* caps=gst_caps_from_string("video/x-h264,stream-format=byte-stream,alignment=au");const bool attached=c.Attach(parser,caps);gst_caps_unref(caps);gst_object_unref(parser);Check(!attached&&FinishReason(c)=="capture-attach-mux-pad-mux-pad","C06 actual unlinked parser remains rejected");}
 Framing();
 return 0;
 }catch(const std::exception& e){std::cerr<<"[fail] "<<e.what()<<'\n';return 1;}}
