// 파일 용도: 녹화 실패 관측의 고정 오류 분류·출력 제한·민감 원문 비노출을 검증한다.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import * as capture from './recording_failure_capture.mjs';
test('LP12-F04 input framing 고정 오류만 안전 집계',()=>{const c=capture.createWriterEvidenceCollector();for(const reason of ['input-caps','input-format','input-alignment','input-codec-data','input-avcc-header','input-nal-width','input-codec-conflict','unknown'])c.append('[recording] file evidence unavailable: capture-attach-input-caps-'+reason+'\n');c.append('[recording] file evidence unavailable: capture-attach-input-caps-input-format /private/canary\n');const v=c.finish();assert.equal(v.total,9);assert.equal(v.counts.length,9);assert(v.counts.every(x=>x.count===1));assert.equal(v.counts.find(x=>x.code==='capture-attach-input-caps-input-nal-width').count,1);assert.equal(v.counts.find(x=>x.code==='unknown').count,1);assert(!JSON.stringify(v).includes('canary'));});
test('LP12-C07 exact phase/code와 unknown 고정 조합만 수집',()=>{const c=capture.createWriterEvidenceCollector();const codes=['capture-accept-vcl-vcl-missing','capture-observe-pts-timestamp-unavailable','capture-observe-dts-timestamp-unavailable','capture-observe-duration-timestamp-unavailable','capture-attach-mux-pad-mux-pad','capture-accept-vcl-unknown'];for(const code of codes)c.append('[recording] file evidence unavailable: '+code+'\n');for(const code of ['capture-accept-vcl-vcl-missing /private/canary','capture-accept-pts-vcl-missing','capture-private-canary-unknown'])c.append('[recording] file evidence unavailable: '+code+'\n');const v=c.finish();for(const code of codes)assert.equal(v.counts.find(x=>x.code===code)?.count,1);assert.equal(v.counts.find(x=>x.code==='unknown').count,3);assert.equal(v.total,9);assert(!JSON.stringify(v).includes('canary'));});
test('LP12-D06 writer fixed 사유만 집계하고 원문을 보존하지 않음',()=>{assert.equal(typeof capture.createWriterEvidenceCollector,'function');const c=capture.createWriterEvidenceCollector();c.append('[recording] file evidence unav');c.append('ailable: file evidence forward table 오류\n[recording] file evidence unavailable: capture-profile-or-cap\n[recording] file evidence unavailable: capture-profile-or-cap /private/canary\n');assert.deepEqual(c.finish(),{basis:'run-wide-stderr',sourceBindingEquivalent:false,total:3,truncated:false,counts:[{code:'capture-profile-or-cap',count:1},{code:'file evidence forward table 오류',count:1},{code:'unknown',count:1}]});assert(!JSON.stringify(c.finish()).includes('canary'));});

const completeness=()=>({state:'complete',snapshotBasis:'offline-copy-at-query',evidenceBasis:'persisted-job-intent-and-ready',reproducibleBundle:false,remuxPerformed:false,capturedIntentSha256:'a'.repeat(64),readySha256:'b'.repeat(64),verifiedOutput:true,requestFullySatisfied:false,selection:{complete:false,reason:'interval-evidence-incomplete',expandedStartNs:'0',expandedEndNs:'100',slices:[{startNs:'0',endNs:'100',state:'unknown',reason:'unconfirmed-interval-no-trusted-watermark',candidateSegmentIdSha256:[]}]},sources:[],unfulfilled:[{segmentIdSha256:null,axis:'request-ns',reason:'unconfirmed-interval-no-trusted-watermark',start:'0',end:'100'}],outputs:[]});
test('LP08-B01 완료 작업 안전 증거 선보존',()=>owned(root=>{assert.equal(typeof capture.captureCompletenessEvidence,'function');const file=path.join(root,'partial.json');const result=capture.captureCompletenessEvidence({collect:completeness,evidencePath:file});assert.equal(result.cleanupAllowed,true);assert.equal(result.evidenceStatus,'preserved');assert.deepEqual(JSON.parse(fs.readFileSync(file)).diagnostic,completeness());assert.equal(fs.statSync(file).mode&0o777,0o600);}));
for(const mode of ['field','enum','range','throw','timeout','existing','symlink'])test(`LP08-B02 ${mode} 증거 실패 시 정리 차단`,()=>owned(root=>{const file=path.join(root,'partial.json');if(mode==='existing')fs.writeFileSync(file,'original');if(mode==='symlink'){fs.writeFileSync(path.join(root,'target'),'original');fs.symlinkSync(path.join(root,'target'),file);}const result=capture.captureCompletenessEvidence({evidencePath:file,collect:()=>{if(mode==='throw')throw Error('private-canary');if(mode==='timeout'){const error=Error('private-canary');error.code='ETIMEDOUT';throw error;}const value=completeness();if(mode==='field')value.raw='private-canary';if(mode==='enum')value.selection.reason='private-canary';if(mode==='range')value.selection.expandedEndNs='-1';return value;}});assert.equal(result.cleanupAllowed,false);assert(!JSON.stringify(result).includes('canary'));if(mode==='existing'||mode==='symlink')assert.equal(fs.readFileSync(file,'utf8'),'original');else assert(!fs.existsSync(file));}));

const originalDiagnostic=()=>({state:'failed',failureReason:'job-source-unavailable',sourceCount:1,outputCount:0,plannedOutputCount:1,fileReceiptCount:0,copyCatalogOpened:true,capturedIntentSha256:'a'.repeat(64),snapshotBasis:'offline-copy-at-query',evidenceBasis:'persisted-job-intent',fileHashBasis:'resolve-media-validated-fd',reproducibleBundle:false,remuxPerformed:false,sourceEvidence:[{segmentIdSha256:'b'.repeat(64),epochSha256:'c'.repeat(64),generationSha256:'d'.repeat(64),trackSha256:'e'.repeat(64),bindingSha256:'f'.repeat(64),generationOrder:'1',startPts:'0',endPts:'100',lastAcceptedOrdinal:'3',timeBaseNum:1,timeBaseDen:1000000000,sampleCount:3,indexComplete:true,fileEvidencePresent:false}],sourceFileHashes:[{segmentIdSha256:'b'.repeat(64),expected:'a'.repeat(64),actual:null,actualHashAvailable:false,matches:null,status:'unavailable'}]});
const catalogProof=()=>({segmentIdSha256:'b'.repeat(64),segmentPresent:true,bindingPresent:true,bindingValid:true,fileEvidencePresent:false,fileEvidenceValid:null,bindingSha256:'f'.repeat(64)});
for(const mode of ['valid','binding-valid','proof-present','binding-hash','matches'])test(`LP12-D02 missing binding ${mode}`,()=>owned(root=>{const o=options(root);o.collect=()=>{const v=diagnostic(),s=v.catalogSourceEvidence[0];Object.assign(s,{bindingPresent:false,bindingValid:null,fileEvidencePresent:false,fileEvidenceValid:null,bindingSha256:null,bindingMatchesIntentWithoutFileEvidence:null});if(mode==='binding-valid')s.bindingValid=true;if(mode==='proof-present'){s.fileEvidencePresent=true;s.fileEvidenceValid=true;}if(mode==='binding-hash')s.bindingSha256='f'.repeat(64);if(mode==='matches')s.bindingMatchesIntentWithoutFileEvidence=false;return v;};const r=capture.captureFailureEvidence(o);assert.equal(r.detailStatus,mode==='valid'?'complete':'failed');assert.equal(r.cleanupAllowed,mode==='valid');if(mode==='valid'){const s=JSON.parse(fs.readFileSync(o.evidencePath+'.details.json')).diagnostic.catalogSourceEvidence[0];assert.equal(s.segmentPresent,true);assert.equal(s.bindingPresent,false);assert.equal(s.bindingValid,null);}}));
for(const status of ['cap-exceeded','unavailable'])test(`LP12-D04 ${status} count 미확인 보존`,()=>owned(root=>{const o=options(root);o.collect=()=>({...diagnostic(),catalogCandidates:{status,count:null,truncated:status==='cap-exceeded',items:[]}});const r=capture.captureFailureEvidence(o);assert.equal(r.detailStatus,'complete');assert.equal(r.cleanupAllowed,true);}));
for(const mode of ['raw','profile','scope','id','validity','lifecycle','count','cap','truncated'])test(`LP12-D05 catalog schema ${mode} 변조 거부`,()=>owned(root=>{const o=options(root);o.collect=()=>{const v=diagnostic();if(mode==='raw')v.catalogSourceEvidence[0].raw='private-canary';if(mode==='profile')v.intentProfile='private-canary';if(mode==='scope')v.catalogCandidateScope='all-channel';if(mode==='id')v.catalogSourceEvidence[0].segmentIdSha256='c'.repeat(64);if(mode==='validity')v.catalogSourceEvidence[0].fileEvidenceValid=true;if(mode==='lifecycle')v.catalogCandidates.items[0].lifecycle=9;if(mode==='count')v.catalogCandidates.count=2;if(mode==='cap'){v.catalogCandidates.items=Array(257).fill(v.catalogCandidates.items[0]);v.catalogCandidates.count=257;}if(mode==='truncated')v.catalogCandidates.truncated=true;return v;};const r=capture.captureFailureEvidence(o);assert.equal(r.detailStatus,'failed');assert.equal(r.cleanupAllowed,false);assert(!JSON.stringify(r).includes('canary'));assert(!fs.existsSync(o.evidencePath+'.details.json'));}));
test('LP12-D06 newline 없는 fixed prefix tail은 known 인정 금지',()=>{const c=capture.createWriterEvidenceCollector();c.append('[recording] file evidence unavailable: capture-profile-or-cap');assert.deepEqual(c.finish(),{basis:'run-wide-stderr',sourceBindingEquivalent:false,total:0,truncated:true,counts:[]});});
test('LP12-D06 line/count cap 및 다음 정상행 복구',()=>{const c=capture.createWriterEvidenceCollector();c.append('private-canary'.repeat(1000)+'\n');c.append('[recording] file evidence unavailable: mp4-table-bound\n'.repeat(4097));const v=c.finish();assert.equal(v.total,4096);assert.equal(v.truncated,true);assert.deepEqual(v.counts,[{code:'mp4-table-bound',count:4096}]);assert(!JSON.stringify(v).includes('canary'));});
function diagnostic(){return {...originalDiagnostic(),intentProfile:'h264-mp4-to-mpegts-video-only-v1',catalogEvidenceBasis:'offline-copy-catalog',failureTimeEquivalent:false,proofValidationBasis:'strict-structure-only',catalogSourceEvidence:[{...catalogProof(),segmentMatchesIntent:true,bindingMatchesIntentWithoutFileEvidence:true}],catalogCandidateScope:'request-related-snapshot',catalogCandidates:{status:'complete',count:1,truncated:false,items:[{...catalogProof(),selected:true,lifecycle:2,deleted:false,eligible:true,startPts:'0',endPts:'100',timeBaseNum:1,timeBaseDen:1000000000}]}};}
function owned(fn){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'recording-capture-')));fs.chmodSync(root,0o700);try{fn(root);}finally{let bytes=0;function size(p){const s=fs.lstatSync(p);if(s.isDirectory())for(const n of fs.readdirSync(p))size(path.join(p,n));else bytes+=s.size;}size(root);fs.rmSync(root,{recursive:true});assert(!fs.existsSync(root));console.log('[cleanup] '+JSON.stringify({root,bytes,removed:true}));}}
function basic(){const v=diagnostic();return Object.fromEntries(['state','failureReason','sourceCount','outputCount','plannedOutputCount','fileReceiptCount','copyCatalogOpened','capturedIntentSha256'].map(k=>[k,v[k]]));}
function stateDiagnostic(state='intent'){return {state,managed:state!=='absent',jobCount:state==='absent'?0:1,referenceSha256:'b'.repeat(64),capturedIntentSha256:state==='absent'?null:'a'.repeat(64),sourceCount:state==='absent'?0:2,outputCount:0,plannedOutputCount:state==='absent'?0:2,fileReceiptCount:0,copyCatalogOpened:true,snapshotBasis:'offline-copy-at-query',failureTimeEquivalent:false,remuxPerformed:false};}
for(const expected of [undefined,'c'.repeat(64),'private-canary'])test(`LP13-P04 expected reference ${expected===undefined?'missing':expected.length===64?'mismatch':'invalid'} 거부`,()=>owned(root=>{const file=path.join(root,'state.json');const r=capture.captureStateEvidence({expectedReferenceSha256:expected,collect:stateDiagnostic,evidencePath:file});assert.equal(r.cleanupAllowed,false);assert(!fs.existsSync(file));assert(!JSON.stringify(r).includes('canary'));}));
for(const state of ['absent','intent','ready','committed','complete','failed'])test(`LP13-P01 generic ${state} HTTP 실패 증거 보존`,()=>owned(root=>{assert.equal(typeof capture.captureStateEvidence,'function');const file=path.join(root,'state.json');const r=capture.captureStateEvidence({expectedReferenceSha256:'b'.repeat(64),collect:()=>stateDiagnostic(state),evidencePath:file});assert.equal(r.cleanupAllowed,true);assert.deepEqual(JSON.parse(fs.readFileSync(file)).diagnostic,stateDiagnostic(state));assert.equal(fs.statSync(file).mode&0o777,0o600);}));
for(const mode of ['field','state','count','hash','absent','throw','timeout','persist'])test(`LP13-P01 generic ${mode} 실패 시 cleanup 차단`,()=>owned(root=>{assert.equal(typeof capture.captureStateEvidence,'function');const file=path.join(root,'state.json');if(mode==='persist')fs.writeFileSync(file,'existing');const r=capture.captureStateEvidence({expectedReferenceSha256:'b'.repeat(64),evidencePath:file,collect:()=>{if(mode==='throw'||mode==='timeout'){const e=Error('private-canary');if(mode==='timeout')e.code='ETIMEDOUT';throw e;}const v=stateDiagnostic();if(mode==='field')v.raw='private-canary';if(mode==='state')v.state='unknown';if(mode==='count')v.sourceCount=4097;if(mode==='hash')v.capturedIntentSha256=null;if(mode==='absent')v.state='absent';return v;}});assert.equal(r.cleanupAllowed,false);assert(!JSON.stringify(r).includes('canary'));}));
function options(root,replay=()=>({persistedFailure:'job-source-unavailable',replayFailure:'job-source-unavailable',verifiedOutput:false,sameFailure:true,persistedRecordUnchanged:true,capturedIntentSha256:'a'.repeat(64),snapshotBasis:'offline-copy-at-query',maxWorkMs:30000,serviceRemainingBudgetEquivalent:false,sourceEvidence:[],sourceFileHashes:[]})){return {evidencePath:path.join(root,'diagnosis.json'),diagnose:basic,collect:diagnostic,replay};}
test('LP06-B01 진단 파일을 재현 전에 보존',()=>owned(root=>{assert.equal(typeof capture.captureFailureEvidence,'function');const o=options(root,()=>{assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.failureReason,'job-source-unavailable');throw Error('private-canary');});const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,true);assert.equal(r.replayStatus,'failed');assert(!JSON.stringify(r).includes('canary'));assert.equal(fs.statSync(o.evidencePath).mode&0o777,0o600);}));
for(const mode of ['exit','timeout'])test(`LP06-B02 실제 자식 ${mode} 뒤 최초 증거 유지`,()=>owned(root=>{const o=options(root,()=>{const r=spawnSync(process.execPath,['-e',mode==='exit'?'process.exit(7)':'setInterval(()=>{},1000)'],{timeout:50,encoding:'utf8'});if(r.error)throw r.error;if(r.status!==0)throw Error('private-canary');});const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,true);assert.equal(r.replayStatus,mode==='timeout'?'timeout':'failed');assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.state,'failed');assert(!fs.readFileSync(o.evidencePath,'utf8').includes('canary'));}));
for(const mode of ['throw','unsafe'])test(`LP06-B03 진단 ${mode} 시 재현·정리 거부`,()=>owned(root=>{let replayed=false;const o=options(root,()=>{replayed=true;});o.diagnose=()=>{if(mode==='throw')throw Error('private-canary');return {...diagnostic(),failureReason:'unknown /private/canary'};};const r=capture.captureFailureEvidence(o);assert.equal(replayed,false);assert.equal(r.cleanupAllowed,false);assert.equal(r.diagnosticStatus,'failed');assert(!fs.existsSync(o.evidencePath));assert(!JSON.stringify(r).includes('canary'));}));
test('LP06-B04 최초 보존 실패 시 재현 금지',()=>owned(root=>{let called=false;const o=options(root,()=>{called=true;});fs.writeFileSync(o.evidencePath,'existing');const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,false);assert.equal(called,false);assert.equal(fs.readFileSync(o.evidencePath,'utf8'),'existing');}));
test('LP06-B04 후속 보존 실패 시 최초 파일 유지',()=>owned(root=>{const o=options(root);fs.writeFileSync(o.evidencePath+'.replay.json','existing');const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,true);assert.equal(r.replayEvidenceStatus,'failed');assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.state,'failed');assert.equal(fs.readFileSync(o.evidencePath+'.replay.json','utf8'),'existing');}));
test('LP06-B05 진단 미보존 root 정리 금지·소유권 불일치 거부',()=>owned(root=>{const target=path.join(root,'run');fs.mkdirSync(target);const stat=fs.lstatSync(target,{bigint:true});assert.throws(()=>capture.removeDiagnosticRoot(target,stat,false),/evidence-not-preserved/);assert(fs.existsSync(target));assert.throws(()=>capture.removeDiagnosticRoot(target,{dev:stat.dev,ino:stat.ino+1n},true),/cleanup-ownership/);assert(fs.existsSync(target));capture.removeDiagnosticRoot(target,stat,true);assert(!fs.existsSync(target));}));
test('LP06-B06 symlink 증거 덮어쓰기 거부',()=>owned(root=>{const o=options(root);const target=path.join(root,'original');fs.writeFileSync(target,'original');fs.symlinkSync(target,o.evidencePath);const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,false);assert.equal(fs.readFileSync(target,'utf8'),'original');assert.deepEqual(fs.readdirSync(root).sort(),['diagnosis.json','original']);}));
test('LP06-B06 성공 결과 분리 보존·미등록 필드 거부',()=>owned(root=>{const o=options(root);const r=capture.captureFailureEvidence(o);assert.equal(r.replayStatus,'complete');assert.equal(r.replayEvidenceStatus,'preserved');assert.equal(JSON.parse(fs.readFileSync(o.evidencePath+'.replay.json')).replay.sameFailure,true);assert.equal(fs.statSync(o.evidencePath+'.replay.json').mode&0o777,0o600);const unsafe=options(root);unsafe.evidencePath=path.join(root,'unsafe.json');unsafe.diagnose=()=>({...diagnostic(),raw:'private-canary'});assert.equal(capture.captureFailureEvidence(unsafe).cleanupAllowed,false);}));
for(const mode of ['throw','timeout','identity','persist'])test(`LP06-B07 상세 수집 ${mode} 시 기본 진단 유지·재현 금지`,()=>owned(root=>{let replayed=false;const o=options(root,()=>{replayed=true;});o.collect=()=>{assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.state,'failed');if(mode==='throw')throw Error('private-canary');if(mode==='timeout'){const r=spawnSync(process.execPath,['-e','setInterval(()=>{},1000)'],{timeout:50});throw r.error;}return {...diagnostic(),capturedIntentSha256:mode==='identity'?'f'.repeat(64):'a'.repeat(64)};};if(mode==='persist')fs.writeFileSync(o.evidencePath+'.details.json','existing');const r=capture.captureFailureEvidence(o);assert.equal(r.diagnosticEvidenceStatus,'preserved');assert.equal(r.cleanupAllowed,false);assert.equal(replayed,false);assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.failureReason,'job-source-unavailable');assert(!JSON.stringify(r).includes('canary'));}));
test('LP06-B08 기본 자식은 plugin 환경 준비 실패와 독립',()=>owned(root=>{assert.equal(typeof capture.runDiagnosticProbe,'function');const script=path.join(root,'child.cjs'),envScript=path.join(root,'env.sh');fs.writeFileSync(script,'process.stdout.write(JSON.stringify({ok:true}))');fs.writeFileSync(envScript,'media_server_apply_homebrew_gst_env(){ return 9; }');const o={binary:process.execPath,root:script,index:1,reference:'ref',environmentScript:envScript,env:{PATH:process.env.PATH},deadline:performance.now()+2000};assert.deepEqual(capture.runDiagnosticProbe({...o,mode:'--diagnose-basic'}),{ok:true});assert.throws(()=>capture.runDiagnosticProbe({...o,mode:'--diagnose-failed'}));}));
test('LP06-B09 만료 시 자식 미기동·남은 시간만 대기',()=>owned(root=>{const script=path.join(root,'child.cjs'),marker=path.join(root,'started');fs.writeFileSync(script,`require('fs').writeFileSync(${JSON.stringify(marker)},'started');setInterval(()=>{},1000);`);const o={binary:process.execPath,root:script,index:1,reference:'ref',mode:'--diagnose-basic',env:{PATH:process.env.PATH},deadline:0};assert.throws(()=>capture.runDiagnosticProbe(o),/diagnostic-deadline/);assert(!fs.existsSync(marker));assert.throws(()=>capture.runDiagnosticProbe({...o,deadline:performance.now()+100}),e=>e.code==='ETIMEDOUT');assert(fs.existsSync(marker));}));
