import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../..');
const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'media-server-archive-probe-tests-')));fs.chmodSync(root,0o700);
const probe=path.join(root,'probe'),fixture=path.join(root,'fixture');
let testEnv;
function scan(dir){const rows=[];function walk(p){for(const name of fs.readdirSync(p).sort()){const full=path.join(p,name),s=fs.lstatSync(full);assert(!s.isSymbolicLink());if(s.isDirectory())walk(full);else rows.push([path.relative(dir,full),s.size,s.ino,s.nlink,crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex')]);}}walk(dir);return rows;}
function run(binary,args){assert(testEnv,'isolated environment must be configured');return spawnSync(binary,args,{env:testEnv,encoding:'utf8',timeout:30000,maxBuffer:1024*1024});}
function setup(mode){const dir=fs.mkdtempSync(path.join(root,'media-server-current-integration-'));fs.chmodSync(dir,0o700);const made=run(fixture,[dir,String(mode)]);assert.equal(made.status,0,'typed fixture must be created');assert.match(made.stdout,/fixtureTypedReadback/);const copy=path.join(dir,'projection-copy-1','recordings');fs.mkdirSync(path.dirname(copy),{mode:0o700});fs.cpSync(path.join(dir,'recordings'),copy,{recursive:true});return {dir,copy,original:path.join(dir,'recordings')};}
function diagnose(f,args=['--diagnose-failed']){return run(probe,[f.dir,'1','job-service-ref',...args]);}
before(()=>{
 const seed={...process.env,MEDIA_SERVER_GST_CACHE_DIR:path.join(root,'gst-cache'),MEDIA_SERVER_GST_PLUGIN_PROFILE:'headless'};
 // Never inherit a registry or managed/plugin search path from another run.
 for(const key of ['GST_REGISTRY','GST_REGISTRY_1_0','GST_PLUGIN_PATH','GST_PLUGIN_PATH_1_0','GST_PLUGIN_SYSTEM_PATH','GST_PLUGIN_SYSTEM_PATH_1_0','MEDIA_SERVER_GST_MANAGED_REGISTRY','MEDIA_SERVER_GST_MANAGED_PLUGIN_PATH','MEDIA_SERVER_GST_INPUT_PLUGIN_PATH'])delete seed[key];
 seed.GST_REGISTRY=seed.GST_REGISTRY_1_0=path.join(root,'registry.bin');
 const environment=execFileSync('bash',['-c','set -e; source "$1"; media_server_apply_homebrew_gst_env; env -0','probe-env',path.join(here,'env_common.sh')],{env:seed,encoding:'utf8',maxBuffer:1024*1024});
 testEnv=Object.fromEntries(environment.split('\0').filter(Boolean).map(entry=>{const i=entry.indexOf('=');assert(i>0);return [entry.slice(0,i),entry.slice(i+1)];}));
 function owned(p){assert(p&&path.resolve(p).startsWith(root+path.sep),'GStreamer writable/cache path must belong to test root');}
 for(const key of ['MEDIA_SERVER_GST_CACHE_DIR','GST_REGISTRY','GST_REGISTRY_1_0'])owned(testEnv[key]);
 assert.equal(testEnv.MEDIA_SERVER_GST_PLUGIN_PROFILE,'headless');
 if(process.platform==='darwin'){assert(testEnv.MEDIA_SERVER_GST_MANAGED_PLUGIN_PATH);for(const p of testEnv.MEDIA_SERVER_GST_MANAGED_PLUGIN_PATH.split(':'))owned(p);assert.equal(testEnv.GST_PLUGIN_SYSTEM_PATH_1_0,'');assert.equal(testEnv.GST_PLUGIN_SYSTEM_PATH,'');}
 console.log('[environment] ownedCache=true ownedRegistry=true headless=true compileAndRunSameEnv=true');
 const archive=path.join(repo,'build-gst-onnx/libmedia_server_runtime.a');const stamp=fs.statSync(archive).mtimeMs;
 function fresh(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())fresh(p);else if(/\.(h|hpp|cpp)$/.test(e.name))assert(fs.statSync(p).mtimeMs<=stamp,'runtime archive must match product source');}}fresh(path.join(repo,'include'));fresh(path.join(repo,'src'));
 const tokens=fs.readFileSync(path.join(repo,'build-gst-onnx/CMakeFiles/media_server.dir/link.txt'),'utf8').trim().split(/\s+/);const index=tokens.indexOf('libmedia_server_runtime.a');assert(index>=0);const libs=[archive,...tokens.slice(index+1)];
 const flags=execFileSync('pkg-config',['--cflags','gstreamer-app-1.0','openssl','sqlite3'],{env:testEnv,encoding:'utf8'}).trim().split(/\s+/);
 for(const [source,out] of [['recording_current_archive_probe.cpp',probe],['recording_current_archive_probe_fixture.cpp',fixture]]){const result=run(process.env.CXX||'c++',['-std=c++17','-Wall','-Wextra','-Werror','-pthread','-I'+path.join(repo,'include'),...flags,'-DMEDIA_SERVER_USE_GSTREAMER=1','-DMEDIA_SERVER_USE_OPENSSL=1','-DMEDIA_SERVER_USE_SQLITE3=1',path.join(here,source),...libs,'-o',out]);if(result.status!==0)process.stderr.write(result.stderr||'compile failed\n');assert.equal(result.status,0,'compile '+source);}
});
after(()=>{let bytes=0;function size(p){const s=fs.lstatSync(p);if(s.isDirectory())for(const n of fs.readdirSync(p))size(path.join(p,n));else bytes+=s.size;}size(root);assert(path.basename(root).startsWith('media-server-archive-probe-tests-')&&!fs.lstatSync(root).isSymbolicLink());fs.rmSync(root,{recursive:true});console.log(`[cleanup] owned_root=${root} bytes=${bytes} removed=${!fs.existsSync(root)}`);assert(!fs.existsSync(root));});
const known=['job-remux: file-original-timestamp-mismatch','job-remux: source-binding-incomplete','job-source-unavailable'];
test('LP06-A08 basic failure survives corrupt media without file inspection',()=>{const f=setup(0),before=scan(f.original);const detailed=JSON.parse(diagnose(f).stdout);for(const row of scan(f.copy).filter(row=>row[0].endsWith('.mp4')))fs.writeFileSync(path.join(f.copy,row[0]),Buffer.from('invalid-media'));fs.mkdirSync(path.join(f.dir,'archive-replay'),{mode:0o700});const r=diagnose(f,['--diagnose-basic']);assert.equal(r.status,0);assert.equal(r.stderr,'');assert.deepEqual(JSON.parse(r.stdout),{state:'failed',failureReason:known[0],sourceCount:2,outputCount:0,plannedOutputCount:2,fileReceiptCount:0,copyCatalogOpened:true,capturedIntentSha256:detailed.capturedIntentSha256});assert.deepEqual(fs.readdirSync(path.join(f.dir,'archive-replay')),[]);assert.deepEqual(scan(f.original),before);});
test('LP06-A08 basic failure survives missing media without file inspection',()=>{const f=setup(0),before=scan(f.original);const detailed=JSON.parse(diagnose(f).stdout);for(const row of scan(f.copy).filter(row=>row[0].endsWith('.mp4')))fs.unlinkSync(path.join(f.copy,row[0]));fs.mkdirSync(path.join(f.dir,'archive-replay'),{mode:0o700});const r=diagnose(f,['--diagnose-basic']);assert.equal(r.status,0,'basic typed failure must not depend on media');assert.equal(r.stderr,'');assert.deepEqual(JSON.parse(r.stdout),{state:'failed',failureReason:known[0],sourceCount:2,outputCount:0,plannedOutputCount:2,fileReceiptCount:0,copyCatalogOpened:true,capturedIntentSha256:detailed.capturedIntentSha256});assert.deepEqual(fs.readdirSync(path.join(f.dir,'archive-replay')),[]);assert.deepEqual(scan(f.original),before);});
function safeEvidence(v){assert.match(v.capturedIntentSha256,/^[a-f0-9]{64}$/);assert.equal(v.snapshotBasis,'offline-copy-at-query');assert.equal(v.evidenceBasis,'persisted-job-intent');assert.equal(v.fileHashBasis,'resolve-media-validated-fd');assert.equal(v.reproducibleBundle,false);assert.equal(v.remuxPerformed,false);assert.equal(v.sourceEvidence.length,2);for(const s of v.sourceEvidence){for(const k of ['segmentIdSha256','epochSha256','generationSha256','trackSha256','bindingSha256'])assert.match(s[k],/^[a-f0-9]{64}$/);for(const k of ['generationOrder','startPts','endPts','lastAcceptedOrdinal'])assert.match(s[k],/^\d+$/);assert.equal(s.timeBaseNum,1);assert.equal(s.timeBaseDen,1000000000);assert(s.sampleCount>0);assert.equal(s.indexComplete,true);assert.equal(typeof s.fileEvidencePresent,'boolean');}assert.equal(v.sourceFileHashes.length,2);}
test('LP06-A01-A02 stored safe evidence and validated file hashes without remux',()=>{const f=setup(0),before=scan(f.original);fs.mkdirSync(path.join(f.dir,'archive-replay'),{mode:0o700});const r=diagnose(f);assert.equal(r.status,0);assert.equal(r.stderr,'');const v=JSON.parse(r.stdout);safeEvidence(v);const hashes=new Set(scan(f.copy).filter(row=>row[0].endsWith('.mp4')).map(row=>row[4]));for(const h of v.sourceFileHashes){assert.equal(h.status,'matched');assert.equal(h.actualHashAvailable,true);assert.equal(h.matches,true);assert.equal(h.actual,h.expected);assert(hashes.has(h.actual));}assert.equal(JSON.parse(diagnose(f).stdout).capturedIntentSha256,v.capturedIntentSha256);assert.deepEqual(fs.readdirSync(path.join(f.dir,'archive-replay')),[]);assert.deepEqual(scan(f.original),before);});
for(const change of ['missing','corrupt'])test(`LP06-${change==='missing'?'A03':'A04'} ${change} copy media preserves failed diagnosis`,()=>{const f=setup(0),before=scan(f.original);const media=scan(f.copy).filter(row=>row[0].endsWith('.mp4'));assert.equal(media.length,3);for(const row of media){const p=path.join(f.copy,row[0]);if(change==='missing')fs.unlinkSync(p);else fs.writeFileSync(p,Buffer.from('invalid-media'));}const r=diagnose(f);assert.equal(r.status,0);assert.equal(r.stderr,'');const v=JSON.parse(r.stdout);safeEvidence(v);assert.equal(v.failureReason,known[0]);for(const h of v.sourceFileHashes){assert.equal(h.status,'unavailable');assert.equal(h.actualHashAvailable,false);assert.equal(h.actual,null);assert.equal(h.matches,null);}assert.deepEqual(scan(f.original),before);});
const moreKnown=['job-cancelled-or-deadline','job-attempt-create','job-output-create','job-remux: media-budget-exceeded','job-remux: work-cancelled','job-remux: output-byte-budget-exceeded'];
for(let i=0;i<moreKnown.length;i++)for(const suffix of [false,true])test(`LP06-${suffix?'A06':'A05'} code${i} ${suffix?'suffix unknown':'exact known'}`,()=>{const f=setup(i+(suffix?12:6)),before=scan(f.original),r=diagnose(f);assert.equal(r.status,0);assert.equal(r.stderr,'');const v=JSON.parse(r.stdout);assert.equal(v.failureReason,suffix?'unknown':moreKnown[i]);assert(!r.stdout.includes('canary')&&!r.stdout.includes('/private/'));assert.deepEqual(scan(f.original),before);});
for(let i=0;i<5;i++)test(`LP05-${i<3?'01':'02'} typed failed ${i<3?'known'+i:'unknown'+i}`,()=>{const f=setup(i),before=scan(f.original),r=diagnose(f);assert.equal(r.status,0,'diagnostic must open typed offline Catalog');assert.equal(r.stderr,'');const value=JSON.parse(r.stdout);safeEvidence(value);const base=Object.fromEntries(['state','failureReason','sourceCount','outputCount','plannedOutputCount','fileReceiptCount','copyCatalogOpened'].map(k=>[k,value[k]]));assert.deepEqual(base,{state:'failed',failureReason:known[i]||'unknown',sourceCount:2,outputCount:0,plannedOutputCount:2,fileReceiptCount:0,copyCatalogOpened:true});assert(!r.stdout.includes('private')&&!r.stdout.includes('canary'));assert.deepEqual(scan(f.original),before,'original bytes/inodes unchanged');});
test('LP05-03 complete mode still rejects failed job',()=>{const f=setup(0),before=scan(f.original),r=diagnose(f,[]);assert.equal(r.status,1);assert.match(r.stderr,/complete-job/);assert.deepEqual(scan(f.original),before);});
test('LP05-03 diagnostic rejects nonfailed state safely',()=>{const f=setup(5),before=scan(f.original),r=diagnose(f);assert.equal(r.status,1);assert.equal(r.stderr,'{"diagnosticError":"archive-probe-failed"}\n');assert.equal(r.stdout,'');assert.deepEqual(scan(f.original),before);});
test('LP05-03 rejects original recordings index without mutation',()=>{const f=setup(0),before=scan(f.original),r=run(probe,[f.dir,'recordings','job-service-ref','--diagnose-failed']);assert.equal(r.status,1);assert.equal(r.stderr,'{"diagnosticError":"archive-probe-failed"}\n');assert.equal(r.stdout,'');assert.deepEqual(scan(f.original),before);});
test('LP05-06 valid media with synthetic failed reason does not reproduce failure',()=>{const f=setup(0),before=scan(f.original),r=diagnose(f,['--replay-failed']);assert.equal(r.status,0,'offline typed remux replay must run');assert.equal(r.stderr,'');const v=JSON.parse(r.stdout);assert.equal(v.persistedFailure,known[0]);assert.equal(v.replayFailure,'none');assert.equal(v.verifiedOutput,true);assert.equal(v.sameFailure,false);assert.equal(v.persistedRecordUnchanged,true);assert.match(v.capturedIntentSha256,/^[a-f0-9]{64}$/);assert.equal(v.sourceEvidence.length,2);assert(v.sourceEvidence.every(s=>s.selected&&/^[a-f0-9]{64}$/.test(s.segmentIdSha256)));assert.equal(v.sourceFileHashes.length,2);assert(v.sourceFileHashes.every(s=>s.matches&&s.expected===s.actual));assert.equal(fs.readdirSync(f.dir).filter(n=>n.startsWith('archive-replay')).length,0);assert.deepEqual(scan(f.original),before);assert.equal(JSON.parse(diagnose(f).stdout).failureReason,known[0]);});
for(const kind of ['symlink','hardlink'])test(`LP05-03 rejects ${kind} copy without original mutation`,()=>{const f=setup(0);if(kind==='symlink'){fs.rmSync(f.copy,{recursive:true});fs.symlinkSync(f.original,f.copy);}else{const entry=scan(f.original)[0][0];fs.unlinkSync(path.join(f.copy,entry));fs.linkSync(path.join(f.original,entry),path.join(f.copy,entry));}const before=scan(f.original),r=diagnose(f);assert.equal(r.status,1);assert.equal(r.stderr,'{"diagnosticError":"archive-probe-failed"}\n');assert.equal(r.stdout,'');assert.deepEqual(scan(f.original),before);});
