// 검증용 제한 MP4 파서: 단일 비분할 video track의 실제 box/tick을 읽는다.
// 제품 입력 검증이나 일반 MP4 지원을 제공하지 않는다. 범위 밖 형식은 오류다.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=process.argv[2];
function need(v,m){if(!v)throw Error(m)}
function hash(b){return crypto.createHash('sha256').update(b).digest('hex')}
function csv(p){const lines=fs.readFileSync(p,'utf8').trim().split('\n');const keys=lines.shift().split(',');return lines.map(l=>Object.fromEntries(l.split(',').map((v,i)=>[keys[i],v])))}
function native(file){
 const b=fs.readFileSync(file);need(b.length<16*1024*1024,'size-bound');const boxes=[];
 function walk(start,end,depth){need(depth<8,'depth');for(let p=start;p<end;){need(p+8<=end,'header');let size=b.readUInt32BE(p),head=8;const type=b.toString('ascii',p+4,p+8);if(size===1){need(p+16<=end,'large');size=Number(b.readBigUInt64BE(p+8));head=16}if(size===0)size=end-p;need(Number.isSafeInteger(size)&&size>=head&&p+size<=end,'box-bound');boxes.push({type,offset:p,size,data:p+head});if(['moov','trak','mdia','minf','stbl','edts'].includes(type))walk(p+head,p+size,depth+1);p+=size;}}
 walk(0,b.length,0);need(boxes.filter(x=>x.type==='trak').length===1&&!boxes.some(x=>['moof','mvex','stz2'].includes(x.type)),'single unfragmented track only');function box(t){const x=boxes.filter(x=>x.type===t);need(x.length===1,'one '+t);return x[0]}
 function entries(t,stride,fn,optional=false){const xs=boxes.filter(x=>x.type===t);if(optional&&!xs.length)return [];const x=box(t),n=b.readUInt32BE(x.data+4);need(n<=10000&&x.data+8+n*stride<=x.offset+x.size,'table '+t);return Array.from({length:n},(_,i)=>fn(x.data+8+i*stride,b[x.data]))}
 const md=box('mdhd'),version=b[md.data];need(version===0||version===1,'mdhd-version');need(md.data+(version?32:20)<=md.offset+md.size,'mdhd-size');const timescale=b.readUInt32BE(md.data+(version?20:12));need(timescale>0,'timescale');const mv=box('mvhd'),mvVersion=b[mv.data];need(mvVersion<2&&mv.data+(mvVersion?32:20)<=mv.offset+mv.size,'mvhd');const movieTimescale=b.readUInt32BE(mv.data+(mvVersion?20:12));need(movieTimescale>0,'movie timescale');
 const stts=entries('stts',8,p=>[b.readUInt32BE(p),b.readUInt32BE(p+4)]),ctts=entries('ctts',8,(p,v)=>{need(v<2,'ctts-version');return [b.readUInt32BE(p),v?b.readInt32BE(p+4):b.readUInt32BE(p+4)]},true);
 const el=boxes.filter(x=>x.type==='elst');let edits=[];if(el.length){const v=b[el[0].data];need(v<2,'elst-version');edits=entries('elst',v?20:12,p=>v?[b.readBigUInt64BE(p).toString(),b.readBigInt64BE(p+8).toString(),b.readInt32BE(p+16)]:[String(b.readUInt32BE(p)),String(b.readInt32BE(p+4)),b.readInt32BE(p+8)])}
 const sz=box('stsz'),constant=b.readUInt32BE(sz.data+4),count=b.readUInt32BE(sz.data+8);need(count<=10000&&sz.data+12+(constant?0:count*4)<=sz.offset+sz.size,'stsz');const sizes=Array.from({length:count},(_,i)=>constant||b.readUInt32BE(sz.data+12+i*4));
 const chunks=boxes.some(x=>x.type==='stco')?entries('stco',4,p=>b.readUInt32BE(p)):entries('co64',8,p=>Number(b.readBigUInt64BE(p)));
 const stsc=entries('stsc',12,p=>[b.readUInt32BE(p),b.readUInt32BE(p+4),b.readUInt32BE(p+8)]);need(stsc.length&&stsc[0][0]===1,'stsc');let sample=0,hashes=[];
 chunks.forEach((offset,i)=>{let s=stsc[0];for(const e of stsc)if(e[0]<=i+1)s=e;for(let j=0;j<s[1];j++){need(sample<count&&offset+sizes[sample]<=b.length,'sample-bound');hashes.push(hash(b.subarray(offset,offset+sizes[sample])));offset+=sizes[sample++];}});need(sample===count,'sample-count');
 need(stts.reduce((s,e)=>s+e[0],0)===count&&(!ctts.length||ctts.reduce((s,e)=>s+e[0],0)===count),'expanded count bound');const durations=stts.flatMap(([n,d])=>{need(d>0,'positive duration');return Array(n).fill(d)}),offsets=ctts.length?ctts.flatMap(([n,d])=>Array(n).fill(d)):Array(count).fill(0);let dts=0;const samples=durations.map((duration,i)=>{const r={index:i,dts,pts:dts+offsets[i],duration,sha256:hashes[i]};dts+=duration;need(Number.isSafeInteger(dts)&&Number.isSafeInteger(r.pts)&&r.pts>=0,'tick-range');return r});return {fileBytes:b.length,fileSHA256:hash(b),timescale,movieTimescale,stts,ctts,edits,boxes,samples};
}
for(let c=1;c<=4;c++){
 const id='TP0'+c,dir=path.join(root,id),original=csv(path.join(dir,'input.csv'));let gaps=0,total=0;
 for(const m of csv(path.join(dir,'manifest.csv'))){const prefix=path.join(dir,'segment-'+m.segment),n=native(path.join(dir,m.file)),d=csv(prefix+'-demux.csv'),p=csv(prefix+'-parse.csv');need(n.samples.length===d.length&&d.length===p.length&&p.length===Number(m.count),'boundary counts');need(n.timescale===(c===2?30000:3000),'literal timescale');if(c<4)need(n.stts.length===1&&n.stts[0][0]===Number(m.count)&&n.stts[0][1]===(c===2?1001:100),'literal stts');else need(JSON.stringify(n.stts)==='[[1,60],[1,150],[1,60],[1,150],[1,60],[1,150],[1,60],[1,150],[1,60],[1,150],[1,60],[1,100]]','literal VFR stts');let durationChanges=0;
 fs.writeFileSync(prefix+'-native.json',JSON.stringify(n,null,2)+'\n');const rows=['index,original_pts,original_dts,original_duration,native_pts_tick,native_dts_tick,native_duration_tick,timescale,native_end_floor_ns,demux_pts,demux_dts,demux_duration,parse_pts,parse_dts,parse_duration,parse_end_ns,next_parse_pts,gap_ns'];
 for(let i=0;i<p.length;i++){need(n.samples[i].sha256===d[i].sha256,'native-demux-payload');const s=n.samples[i],o=original[Number(m.ordinal)-1+i],end=BigInt(p[i].pts)+BigInt(p[i].duration),next=i+1<p.length?BigInt(p[i+1].pts):null;const ns=t=>BigInt(t)*1000000000n/BigInt(n.timescale);need(BigInt(d[i].pts)===ns(s.pts)&&BigInt(d[i].dts)===ns(s.dts)&&BigInt(d[i].duration)===ns(s.dts+s.duration)-ns(s.dts),'native-demux timing');need(d[i].pts===p[i].pts&&d[i].dts===p[i].dts,'demux-parse pts dts');need(p[i].duration===(c===2?'33366666':'33333333'),'literal parser duration');if(d[i].duration!==p[i].duration)durationChanges++;const gap=next===null?'null':String(next-end);if(gap==='1')gaps++;rows.push([i,o.pts,o.dts,o.duration,s.pts,s.dts,s.duration,n.timescale,((BigInt(s.pts)+BigInt(s.duration))*1000000000n/BigInt(n.timescale)).toString(),d[i].pts,d[i].dts,d[i].duration,p[i].pts,p[i].dts,p[i].duration,end.toString(),next===null?'null':next.toString(),gap].join(','));}
 const ns=t=>BigInt(t)*1000000000n/BigInt(n.timescale);let endpointMismatch=0,originMismatch=0;for(let i=0;i<d.length;i++){const s=n.samples[i];if(BigInt(d[i].pts)+BigInt(d[i].duration)!==ns(s.pts+s.duration))endpointMismatch++;if(BigInt(original[Number(m.ordinal)-1+i].pts)!==BigInt(m.media_start)+ns(s.pts))originMismatch++;}
 console.log(`[boundary] ${id} segment=${m.segment} native_demux_pts_dts_duration_mismatch=0 demux_parse_pts_dts_mismatch=0 demux_parse_duration_changed=${durationChanges} demux_end_native_presentation_end_mismatch=${endpointMismatch} original_pts_minus_media_start_vs_native_pts_mismatch=${originMismatch}`);
 fs.writeFileSync(prefix+'-comparison.csv',rows.join('\n')+'\n');total+=p.length;console.log(`[native] ${id} segment=${m.segment} timescale=${n.timescale} samples=${p.length} sha256=${n.fileSHA256} bytes=${n.fileBytes} stts=${JSON.stringify(n.stts)} ctts=${JSON.stringify(n.ctts)} elst=${JSON.stringify(n.edits)} payload_native_demux_equal=true`);
 }
 if(c===4){const parsed=csv(path.join(dir,'input-parser.csv'));need(parsed.length===12,'input parser count');for(let i=0;i<12;i++)need(parsed[i].pts===original[i].pts&&parsed[i].dts===original[i].dts&&parsed[i].duration==='33333333','input parser literal');need(original[11].duration==='70000000','last duration input');console.log('[input-parser] TP04 count=12 pts_dts_unchanged=true duration_all=33333333 last_input_duration=70000000');}
 need(total===original.length,'input count');if(c===1)need(gaps>0,'TP01 expected 1ns gaps');console.log(`[pass] ${id} characterization samples=${total} observed_1ns_gaps=${gaps}`);
}
console.log('[summary] pass=4 fail=0 scope=timing-characterization-only');
