import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import * as capture from './recording_failure_capture.mjs';

const completeness=()=>({state:'complete',snapshotBasis:'offline-copy-at-query',evidenceBasis:'persisted-job-intent-and-ready',reproducibleBundle:false,remuxPerformed:false,capturedIntentSha256:'a'.repeat(64),readySha256:'b'.repeat(64),verifiedOutput:true,requestFullySatisfied:false,selection:{complete:false,reason:'interval-evidence-incomplete',expandedStartNs:'0',expandedEndNs:'100',slices:[{startNs:'0',endNs:'100',state:'unknown',reason:'unconfirmed-interval-no-trusted-watermark',candidateSegmentIdSha256:[]}]},sources:[],unfulfilled:[{segmentIdSha256:null,axis:'request-ns',reason:'unconfirmed-interval-no-trusted-watermark',start:'0',end:'100'}],outputs:[]});
test('LP08-B01 완료 작업 안전 증거 선보존',()=>owned(root=>{assert.equal(typeof capture.captureCompletenessEvidence,'function');const file=path.join(root,'partial.json');const result=capture.captureCompletenessEvidence({collect:completeness,evidencePath:file});assert.equal(result.cleanupAllowed,true);assert.equal(result.evidenceStatus,'preserved');assert.deepEqual(JSON.parse(fs.readFileSync(file)).diagnostic,completeness());assert.equal(fs.statSync(file).mode&0o777,0o600);}));
for(const mode of ['field','enum','range','throw','timeout','existing','symlink'])test(`LP08-B02 ${mode} 증거 실패 시 정리 차단`,()=>owned(root=>{const file=path.join(root,'partial.json');if(mode==='existing')fs.writeFileSync(file,'original');if(mode==='symlink'){fs.writeFileSync(path.join(root,'target'),'original');fs.symlinkSync(path.join(root,'target'),file);}const result=capture.captureCompletenessEvidence({evidencePath:file,collect:()=>{if(mode==='throw')throw Error('private-canary');if(mode==='timeout'){const error=Error('private-canary');error.code='ETIMEDOUT';throw error;}const value=completeness();if(mode==='field')value.raw='private-canary';if(mode==='enum')value.selection.reason='private-canary';if(mode==='range')value.selection.expandedEndNs='-1';return value;}});assert.equal(result.cleanupAllowed,false);assert(!JSON.stringify(result).includes('canary'));if(mode==='existing'||mode==='symlink')assert.equal(fs.readFileSync(file,'utf8'),'original');else assert(!fs.existsSync(file));}));

const diagnostic=()=>({state:'failed',failureReason:'job-source-unavailable',sourceCount:1,outputCount:0,plannedOutputCount:1,fileReceiptCount:0,copyCatalogOpened:true,capturedIntentSha256:'a'.repeat(64),snapshotBasis:'offline-copy-at-query',evidenceBasis:'persisted-job-intent',fileHashBasis:'resolve-media-validated-fd',reproducibleBundle:false,remuxPerformed:false,sourceEvidence:[{segmentIdSha256:'b'.repeat(64),epochSha256:'c'.repeat(64),generationSha256:'d'.repeat(64),trackSha256:'e'.repeat(64),bindingSha256:'f'.repeat(64),generationOrder:'1',startPts:'0',endPts:'100',lastAcceptedOrdinal:'3',timeBaseNum:1,timeBaseDen:1000000000,sampleCount:3,indexComplete:true,fileEvidencePresent:false}],sourceFileHashes:[{segmentIdSha256:'b'.repeat(64),expected:'a'.repeat(64),actual:null,actualHashAvailable:false,matches:null,status:'unavailable'}]});
function owned(fn){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'recording-capture-')));fs.chmodSync(root,0o700);try{fn(root);}finally{let bytes=0;function size(p){const s=fs.lstatSync(p);if(s.isDirectory())for(const n of fs.readdirSync(p))size(path.join(p,n));else bytes+=s.size;}size(root);fs.rmSync(root,{recursive:true});assert(!fs.existsSync(root));console.log('[cleanup] '+JSON.stringify({root,bytes,removed:true}));}}
function basic(){const v=diagnostic();return Object.fromEntries(['state','failureReason','sourceCount','outputCount','plannedOutputCount','fileReceiptCount','copyCatalogOpened','capturedIntentSha256'].map(k=>[k,v[k]]));}
function options(root,replay=()=>({persistedFailure:'job-source-unavailable',replayFailure:'job-source-unavailable',verifiedOutput:false,sameFailure:true,persistedRecordUnchanged:true,capturedIntentSha256:'a'.repeat(64),snapshotBasis:'offline-copy-at-query',maxWorkMs:30000,serviceRemainingBudgetEquivalent:false,sourceEvidence:[],sourceFileHashes:[]})){return {evidencePath:path.join(root,'diagnosis.json'),diagnose:basic,collect:diagnostic,replay};}
test('LP06-B01 진단 파일을 재현 전에 보존',()=>owned(root=>{assert.equal(typeof capture.captureFailureEvidence,'function');const o=options(root,()=>{assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.failureReason,'job-source-unavailable');throw Error('private-canary');});const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,true);assert.equal(r.replayStatus,'failed');assert(!JSON.stringify(r).includes('canary'));assert.equal(fs.statSync(o.evidencePath).mode&0o777,0o600);}));
for(const mode of ['exit','timeout'])test(`LP06-B02 실제 자식 ${mode} 뒤 최초 증거 유지`,()=>owned(root=>{const o=options(root,()=>{const r=spawnSync(process.execPath,['-e',mode==='exit'?'process.exit(7)':'setInterval(()=>{},1000)'],{timeout:50,encoding:'utf8'});if(r.error)throw r.error;if(r.status!==0)throw Error('private-canary');});const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,true);assert.equal(r.replayStatus,mode==='timeout'?'timeout':'failed');assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.state,'failed');assert(!fs.readFileSync(o.evidencePath,'utf8').includes('canary'));}));
for(const mode of ['throw','unsafe'])test(`LP06-B03 진단 ${mode} 시 재현·정리 거부`,()=>owned(root=>{let replayed=false;const o=options(root,()=>{replayed=true;});o.diagnose=()=>{if(mode==='throw')throw Error('private-canary');return {...diagnostic(),failureReason:'unknown /private/canary'};};const r=capture.captureFailureEvidence(o);assert.equal(replayed,false);assert.equal(r.cleanupAllowed,false);assert.equal(r.diagnosticStatus,'failed');assert(!fs.existsSync(o.evidencePath));assert(!JSON.stringify(r).includes('canary'));}));
test('LP06-B04 최초 보존 실패 시 재현 금지',()=>owned(root=>{let called=false;const o=options(root,()=>{called=true;});fs.writeFileSync(o.evidencePath,'existing');const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,false);assert.equal(called,false);assert.equal(fs.readFileSync(o.evidencePath,'utf8'),'existing');}));
test('LP06-B04 후속 보존 실패 시 최초 파일 유지',()=>owned(root=>{const o=options(root);fs.writeFileSync(o.evidencePath+'.replay.json','existing');const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,true);assert.equal(r.replayEvidenceStatus,'failed');assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.state,'failed');assert.equal(fs.readFileSync(o.evidencePath+'.replay.json','utf8'),'existing');}));
test('LP06-B05 진단 미보존 root 정리 금지·소유권 불일치 거부',()=>owned(root=>{const target=path.join(root,'run');fs.mkdirSync(target);const stat=fs.lstatSync(target,{bigint:true});assert.throws(()=>capture.removeDiagnosticRoot(target,stat,false),/evidence-not-preserved/);assert(fs.existsSync(target));assert.throws(()=>capture.removeDiagnosticRoot(target,{dev:stat.dev,ino:stat.ino+1n},true),/cleanup-ownership/);assert(fs.existsSync(target));capture.removeDiagnosticRoot(target,stat,true);assert(!fs.existsSync(target));}));
test('LP06-B06 symlink 증거 덮어쓰기 거부',()=>owned(root=>{const o=options(root);const target=path.join(root,'original');fs.writeFileSync(target,'original');fs.symlinkSync(target,o.evidencePath);const r=capture.captureFailureEvidence(o);assert.equal(r.cleanupAllowed,false);assert.equal(fs.readFileSync(target,'utf8'),'original');assert.deepEqual(fs.readdirSync(root).sort(),['diagnosis.json','original']);}));
test('LP06-B06 성공 결과 분리 보존·미등록 필드 거부',()=>owned(root=>{const o=options(root);const r=capture.captureFailureEvidence(o);assert.equal(r.replayStatus,'complete');assert.equal(r.replayEvidenceStatus,'preserved');assert.equal(JSON.parse(fs.readFileSync(o.evidencePath+'.replay.json')).replay.sameFailure,true);assert.equal(fs.statSync(o.evidencePath+'.replay.json').mode&0o777,0o600);const unsafe=options(root);unsafe.evidencePath=path.join(root,'unsafe.json');unsafe.diagnose=()=>({...diagnostic(),raw:'private-canary'});assert.equal(capture.captureFailureEvidence(unsafe).cleanupAllowed,false);}));
for(const mode of ['throw','timeout','identity','persist'])test(`LP06-B07 상세 수집 ${mode} 시 기본 진단 유지·재현 금지`,()=>owned(root=>{let replayed=false;const o=options(root,()=>{replayed=true;});o.collect=()=>{assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.state,'failed');if(mode==='throw')throw Error('private-canary');if(mode==='timeout'){const r=spawnSync(process.execPath,['-e','setInterval(()=>{},1000)'],{timeout:50});throw r.error;}return {...diagnostic(),capturedIntentSha256:mode==='identity'?'f'.repeat(64):'a'.repeat(64)};};if(mode==='persist')fs.writeFileSync(o.evidencePath+'.details.json','existing');const r=capture.captureFailureEvidence(o);assert.equal(r.diagnosticEvidenceStatus,'preserved');assert.equal(r.cleanupAllowed,false);assert.equal(replayed,false);assert.equal(JSON.parse(fs.readFileSync(o.evidencePath)).diagnostic.failureReason,'job-source-unavailable');assert(!JSON.stringify(r).includes('canary'));}));
test('LP06-B08 기본 자식은 plugin 환경 준비 실패와 독립',()=>owned(root=>{assert.equal(typeof capture.runDiagnosticProbe,'function');const script=path.join(root,'child.cjs'),envScript=path.join(root,'env.sh');fs.writeFileSync(script,'process.stdout.write(JSON.stringify({ok:true}))');fs.writeFileSync(envScript,'media_server_apply_homebrew_gst_env(){ return 9; }');const o={binary:process.execPath,root:script,index:1,reference:'ref',environmentScript:envScript,env:{PATH:process.env.PATH},deadline:performance.now()+2000};assert.deepEqual(capture.runDiagnosticProbe({...o,mode:'--diagnose-basic'}),{ok:true});assert.throws(()=>capture.runDiagnosticProbe({...o,mode:'--diagnose-failed'}));}));
test('LP06-B09 만료 시 자식 미기동·남은 시간만 대기',()=>owned(root=>{const script=path.join(root,'child.cjs'),marker=path.join(root,'started');fs.writeFileSync(script,`require('fs').writeFileSync(${JSON.stringify(marker)},'started');setInterval(()=>{},1000);`);const o={binary:process.execPath,root:script,index:1,reference:'ref',mode:'--diagnose-basic',env:{PATH:process.env.PATH},deadline:0};assert.throws(()=>capture.runDiagnosticProbe(o),/diagnostic-deadline/);assert(!fs.existsSync(marker));assert.throws(()=>capture.runDiagnosticProbe({...o,deadline:performance.now()+100}),e=>e.code==='ETIMEDOUT');assert(fs.existsSync(marker));}));
