#include "recording_media_test_fixture.h"
#include "recording/recording_derived_job_service.h"
#include "recording/recording_derived_event_worker.h"
#include "recording/recording_derived_selection.h"
#include <iostream>
#include <thread>
#include <fstream>
using namespace recording;
namespace {
void Need(bool v){if(!v)throw std::runtime_error("fixture-oracle");}
void Pass(const char* label){std::cout<<"[pass] "<<label<<std::endl;}
std::string Hash(const std::string& s){auto* sum=g_checksum_new(G_CHECKSUM_SHA256);g_checksum_update(sum,reinterpret_cast<const guchar*>(s.data()),s.size());std::string h=g_checksum_get_string(sum);g_checksum_free(sum);return h;}
auto Evidence(const Encoded& input){analysis::DecodedIntervalCollector c;for(const auto& p:input.packets){analysis::DecodedIntervalEvidence e;e.analysis_pts_ns=p.pts;e.duration_ns=p.observation->duration_ns;e.association={analysis::SourceAssociationQuality::TimestampMatch,analysis::OriginalSampleIdentity{p.observation->source_generation,p.observation->generation_order,p.observation->ordinal,p.track_id,*p.observation->pts_ns}};c.Append(e);}return c.Snapshot("reproduction-r0");}
RecordingConsumerReferenceV1 Reference(int index,std::int64_t start,std::int64_t end){RecordingConsumerReferenceV1 r;r.reference_id="reproduction-ref-"+std::to_string(index);r.kind="event";r.owner_id="reproduction-event-"+std::to_string(index);r.source_id=r.channel_id="probe-channel";r.analysis_namespace="reproduction-r0";r.analysis_track_id="track-1";r.association_quality="timestamp-match";r.original=RecordingConsumerOriginalV1{"probe-generation-a",1,1,"video-0",0};r.request=RecordingConsumerRequestV1{"media-pts-ms",start,end,0,0};return r;}
auto Sources(Store& s){std::vector<DerivedSourceEvidence> out;for(const auto& segment:s.Segments())out.push_back({segment,s.catalog.FindSourceBinding(segment.segment_id),false});return out;}
auto Writer(Store& s,const Encoded& input){GStreamerSegmentWriter::Options o(s.root,2000);o.managed_journal=&s.journal;o.managed_catalog=&s.catalog;o.managed_store_id="probe-store";auto w=std::make_unique<GStreamerSegmentWriter>(o);std::string e;Need(w->Start("probe-channel","unused",input.descriptor,[](auto,auto,auto*){return false;},&e));return w;}
auto Retention(Store& s){auto r=std::make_unique<RetentionCoordinator>(s.catalog,[&]{return s.catalog.RetentionSnapshot();},[](auto* n,auto*){*n=1024ULL*1024*1024;return true;},[](const auto&,auto*){return false;},RetentionCoordinator::Options{0,1,s.root});std::string e;Need(r->UpdateChannelPolicy("probe-channel",{1024ULL*1024*1024,0,1024ULL*1024*1024,0},&e));return r;}
void Measure(const DerivedJobRecordV1& job){const auto payload=SerializeDerivedJobRecord(job);Need(!payload.empty());std::size_t samples=0,maps=0,aus=0;for(const auto& s:job.intent.sources){samples+=s.binding.samples.size();maps+=s.segment.mappings.size();}if(job.ready)for(const auto& o:job.ready->outputs)aus+=o.provenance.access_units.size();DerivedRecordingSelection selection;Need(RestoreDerivedJobSelection(job.intent,&selection,nullptr));std::cout<<"[shape] state="<<static_cast<int>(job.state)<<" bytes="<<payload.size()<<" sources="<<job.intent.sources.size()<<" samples="<<samples<<" mappings="<<maps<<" slices="<<selection.slices.size()<<" aus="<<aus<<" hash="<<Hash(payload)<<std::endl;
 for(int i=0;i<3;++i){auto t=std::chrono::steady_clock::now();Need(SerializeDerivedJobRecord(job)==payload);auto middle=std::chrono::steady_clock::now();DerivedJobRecordV1 parsed;Need(ParseDerivedJobRecord(payload,&parsed,nullptr));std::cout<<"[record-cost] iteration="<<i+1<<" serialize_us="<<std::chrono::duration_cast<std::chrono::microseconds>(middle-t).count()<<" parse_us="<<std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now()-middle).count()<<std::endl;}}
void CheckpointCase(const std::filesystem::path& root,Encoded input){for(std::size_t i=0;i<input.packets.size();++i){auto& o=*input.packets[i].observation;o.mono_before_ns=1000000000LL+i*1000000LL;o.mono_after_ns=o.mono_before_ns+1000;o.observed_utc_ns=1789200000000000000LL+i*1000000LL;}Store s(root);auto w=Writer(s,input);for(const auto& p:input.packets)w->Push(p,0);w->Stop();auto sources=Sources(s);Need(sources.size()==3&&sources[0].binding->samples.size()==250&&sources[1].binding->samples.size()==250&&sources[0].segment.mappings.size()==250&&sources[1].segment.mappings.size()==250);auto retention=Retention(s);std::vector<DerivedJobRecordV1> captured;std::string id;
 DerivedJobService service(s.catalog,s.journal,{root,30000,[&](auto stage,auto){if(stage==DerivedJobProgress::ReadyDurable||stage==DerivedJobProgress::CompleteDurable){std::optional<DerivedJobRecordV1> job;Need(s.catalog.FindDerivedJob(id,&job,nullptr)&&job.has_value());captured.push_back(*job);}}});
 for(int i=0;i<2;++i){DerivedRecordingSelection selected;Need(SelectDerivedRecording(Reference(i,3000,4500),*Evidence(input),sources,nullptr,&selected,nullptr)&&selected.complete);DerivedJobIntentV1 intent;Need(BuildDerivedJobIntent(selected,sources,8*1024*1024,10+i,&intent,nullptr));id=intent.job_id;Need(retention->AdmitDerivedJob(s.catalog,intent,10+i).accepted);auto result=service.Run(id);Need(result.complete&&result.job&&result.job->ready&&s.catalog.RetentionSnapshot().durable_reservations.empty());for(const auto& output:result.job->ready->outputs){const auto path=s.catalog.FindSegmentMediaPath(output.segment.segment_id);(void)path;const auto location=s.catalog.FindSegmentMediaLocation(output.segment.segment_id);Need(location.has_value());std::ifstream file(location->first/location->second,std::ios::binary);std::string bytes((std::istreambuf_iterator<char>(file)),{});Need(Hash(bytes)==output.segment.checksum_sha256);} }
 Need(captured.size()==4);for(const auto& record:captured)Measure(record);Pass("CP01 actual Ready Complete shape canonical files reservation");Pass("CP02 bounded two jobs automatic checkpoint trace collected");}
void PartialCase(const std::filesystem::path& root,const Encoded& input){Store s(root);auto w=Writer(s,input);Encoded observed=input;observed.packets.resize(300);for(const auto& p:observed.packets)w->Push(p,0);auto before=Sources(s);Need(before.size()==1);auto evidence=Evidence(observed);auto reference=Reference(20,7816,9316);reference.original=RecordingConsumerOriginalV1{"probe-generation-a",1,258,"video-0",8566666666ULL};DerivedRecordingSelection initial;Need(SelectDerivedRecording(reference,*evidence,before,nullptr,&initial,nullptr)&&!initial.complete);auto retention=Retention(s);DerivedJobService service(s.catalog,s.journal,{root,30000,{}});auto options=RecordingRuntimeEventBudget(2000,750);Need(options.wait_ms==3750);options.latest_evidence=[&](const auto&){return DerivedEventEvidenceUpdate{"probe-channel","probe-channel",evidence};};DerivedEventWorker worker(s.catalog,*retention,service,options);Need(s.catalog.PutConsumerReference(reference,nullptr));Need(worker.Submit(reference,evidence,nullptr));RecordingDerivedReferenceResult result;const auto start=std::chrono::steady_clock::now();do{result=worker.Query(reference.reference_id);if(!result.jobs.empty()&&result.jobs.front().job.state==DerivedJobState::Complete)break;std::this_thread::sleep_for(std::chrono::milliseconds(20));}while(std::chrono::steady_clock::now()-start<std::chrono::seconds(15));worker.StopAndDrain();Need(result.jobs.size()==1&&result.jobs[0].job.ready&&!result.jobs[0].job.ready->request_fully_satisfied&&result.jobs[0].outputs.size()==1&&Sources(s).size()==1);DerivedRecordingSelection partial;Need(RestoreDerivedJobSelection(result.jobs[0].job.intent,&partial,nullptr));std::int64_t cursor=8333333333LL;std::size_t missing=0;
 for(const auto& slice:partial.slices)if(slice.state!=DerivedSliceState::Confirmed){Need(slice.reason=="unconfirmed-interval-no-trusted-watermark"&&slice.start_ns==cursor);cursor=slice.end_ns;++missing;std::cout<<"[partial] state="<<static_cast<int>(slice.state)<<" reason="<<slice.reason<<" start="<<slice.start_ns<<" end="<<slice.end_ns<<std::endl;}
 Need(cursor==9316000000LL&&missing>0);cursor=8333333333LL;std::size_t unfulfilled=0;
 for(const auto& u:result.jobs[0].job.ready->unfulfilled){std::cout<<"[unfulfilled] axis="<<u.axis<<" reason="<<u.reason<<" start="<<u.start<<" end="<<u.end<<std::endl;if(u.axis=="request-ns"){Need(u.reason=="unconfirmed-interval-no-trusted-watermark"&&u.start==cursor);cursor=u.end;++unfulfilled;}}
 Need(cursor==9316000000LL&&unfulfilled==missing);
 std::cout<<"[worker-elapsed] ms="<<std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-start).count()<<std::endl;
 Need(before[0].binding->samples.size()==250&&before[0].binding->last_accepted_ordinal==250);
 w->Stop();auto after=Sources(s);DerivedRecordingSelection complete;Need(after.size()==2&&SelectDerivedRecording(reference,*evidence,after,nullptr,&complete,nullptr)&&complete.complete);Need(after[1].binding->samples.size()==50&&after[1].binding->last_accepted_ordinal==300);std::cout<<"[partial-context] before_sources=1 after_sources=2 evidence_frames="<<evidence->frames.size()<<" wait_ms="<<options.wait_ms<<std::endl;Pass("CP03 bounded partial missing source then same evidence complete");}
}
int main(int argc,char** argv){if(argc!=2)return 2;gst_init(nullptr,nullptr);try{auto input=Encode(501,false,false,160,90,30,250);Shift(input,0);Need(input.packets[250].is_key_frame&&input.packets[500].is_key_frame);CheckpointCase(std::filesystem::path(argv[1])/"checkpoint",input);PartialCase(std::filesystem::path(argv[1])/"partial",input);std::cout<<"[summary] pass=3 fail=0\n";return 0;}catch(const std::exception& e){std::cout<<"[setup-or-oracle-fail] "<<e.what()<<"\n";return 1;}}
